# Generated by Django 3.1.3 on 2020-11-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.CharField(max_length=50, null=True, verbose_name='信息'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=50, null=True, verbose_name='性别'),
        ),
    ]
